export const threadShowFixture = {
  thread: {
    threadId: `thread:${"a".repeat(64)}`,
    resolvedFromThreadId: `thread:${"b".repeat(64)}`,
    subject: "Quarterly review",
    participants: [{ name: "Ava", address: "ava@example.com" }],
    participantsTruncated: false,
    messageCount: 2,
    messageIds: ["message:first", "message:second"],
    messages: [
      {
        messageId: "message:first",
        threadId: `thread:${"a".repeat(64)}`,
        subject: "Quarterly review",
        from: { name: "Ava", address: "ava@example.com" },
        to: [{ address: "team@example.com" }],
        cc: [],
        sentAt: "2026-08-18T00:00:00.000Z",
        receivedAt: "2026-08-18T00:00:01.000Z",
        textBody: "first",
        htmlBody: null,
        snippet: "first",
        isUnread: true,
        labels: [],
        attachments: [],
      },
      {
        messageId: "message:second",
        threadId: `thread:${"a".repeat(64)}`,
        subject: "Re: Quarterly review",
        from: { address: "team@example.com" },
        to: [{ name: "Ava", address: "ava@example.com" }],
        cc: [],
        sentAt: "2026-08-18T01:00:00.000Z",
        receivedAt: "2026-08-18T01:00:01.000Z",
        textBody: "second",
        htmlBody: null,
        snippet: "second",
        isUnread: false,
        labels: [],
        attachments: [],
      },
    ],
    firstReceivedAt: "2026-08-18T00:00:01.000Z",
    lastReceivedAt: "2026-08-18T01:00:01.000Z",
    nextCursor: null,
  },
} as const;

export const unknownThreadError = {
  code: "not_found",
  message: "thread was not found",
  correlationId: "corr:unknown",
  details: { resource: "thread", id: `thread:${"c".repeat(64)}` },
} as const;
