import { Hono, type Context } from "hono";
import {
  correlationIdSchema,
  createOperationRegistry,
  defineOperation,
  publicErrorEnvelopeSchema,
  reportAdminMessageIdSchema,
  reportAdminSourceCitationSchema,
  reportAdminReportIdSchema,
  REPORT_CONTENT_SECURITY_POLICY,
  renderReport,
} from "@agent-mail/contracts";
import {
  createRegistryTransportAdapter,
  httpErrorRegistry,
  type HttpCredentialAuthenticator,
  type PrivateHttpLogger,
  type OperationHandlerContext,
  type HttpPrincipal,
  type OperationHandlerMap,
} from "./http";
import { z } from "zod";
import { createHash } from "node:crypto";
import {
  canonicalJsonBytes,
  canonicalJsonStringBytes,
} from "../../storage/src/report-creation-repository";

const REPORT_READ_SCOPE = "reports:read";
const SOURCE_READ_SCOPE = "mail:read.message";
const MAX_REPORT_BYTES = 16 * 1024 * 1024;
const MAX_SOURCE_BYTES = 10 * 1024 * 1024;

const scopeSchema = z
  .string()
  .min(1)
  .max(256)
  .regex(/^[a-z][a-z0-9]*(?:[._:-][a-z0-9]+)*$/u);
const ownerSchema = z.string().min(1).max(256);

const reportTextSchema = z.string().max(MAX_REPORT_BYTES);
const reportClaimSchema = z.strictObject({
  text: reportTextSchema,
  citations: z.array(reportAdminSourceCitationSchema).min(1),
});
const reportSectionSchema = z.strictObject({
  heading: reportTextSchema,
  claims: z.array(reportClaimSchema).min(1),
});

/**
 * The stored artifact carries only the renderer's structured input. There is
 * deliberately no filesystem path or arbitrary HTML field in this record;
 * served HTML is generated by the accepted renderer at request time.
 */
export const reportArtifactRecordSchema = z.strictObject({
  reportId: reportAdminReportIdSchema,
  owner: ownerSchema,
  scope: scopeSchema,
  model: z.strictObject({
    title: reportTextSchema,
    summary: reportTextSchema,
    sections: z.array(reportSectionSchema).min(1),
  }),
});
export type ReportArtifactRecord = z.infer<typeof reportArtifactRecordSchema>;

/**
 * The source projection contains text only. In particular, a record has no
 * html/raw/path field that could accidentally turn a citation into a proxy.
 */
export const sourceTextRecordSchema = z.strictObject({
  messageId: reportAdminMessageIdSchema,
  owner: ownerSchema,
  scope: scopeSchema,
  text: z.string().max(MAX_SOURCE_BYTES),
});
export type SourceTextRecord = z.infer<typeof sourceTextRecordSchema>;

export type ReportServingRepository = Readonly<{
  readonly resolveReport: (
    reportId: string,
    principalJson?: Uint8Array,
  ) => ReportArtifactRecord | undefined | Promise<ReportArtifactRecord | undefined>;
  readonly resolveSource: (
    messageId: string,
    principalJson?: Uint8Array,
  ) => SourceTextRecord | undefined | Promise<SourceTextRecord | undefined>;
}>;

export type ReportServingAppOptions = Readonly<{
  readonly repository: ReportServingRepository;
  readonly authenticate?: HttpCredentialAuthenticator;
  readonly logger?: PrivateHttpLogger;
}>;

const reportRequestSchema = z.strictObject({ reportId: reportAdminReportIdSchema });
const sourceRequestSchema = z.strictObject({ messageId: reportAdminMessageIdSchema });

const reportResponseSchema = z.union([
  z.strictObject({
    kind: z.literal("report"),
    reportId: reportAdminReportIdSchema,
    body: z.string().min(1).max(MAX_REPORT_BYTES),
  }),
  publicErrorEnvelopeSchema,
]);
const sourceResponseSchema = z.union([
  z.strictObject({
    kind: z.literal("source"),
    messageId: reportAdminMessageIdSchema,
    body: z.string().max(MAX_SOURCE_BYTES),
  }),
  publicErrorEnvelopeSchema,
]);

const reportServeOperation = defineOperation({
  key: "reports.serve",
  route: "/v1/reports/{reportId}",
  method: "GET",
  cliName: "reports-serve",
  scope: REPORT_READ_SCOPE,
  request: reportRequestSchema,
  response: reportResponseSchema,
  streaming: "bytes" as const,
  strictness: "strict" as const,
});

const sourceTextOperation = defineOperation({
  key: "messages.text",
  route: "/v1/messages/{messageId}/text",
  method: "GET",
  cliName: "messages-text",
  scope: SOURCE_READ_SCOPE,
  request: sourceRequestSchema,
  response: sourceResponseSchema,
  streaming: "bytes" as const,
  strictness: "strict" as const,
});

const reportServingRegistry = createOperationRegistry([reportServeOperation, sourceTextOperation]);

type ServingOperationKey = "reports.serve" | "messages.text";

const RESPONSE_HEADERS = Object.freeze({
  "Cache-Control": "private, no-store",
  "X-Content-Type-Options": "nosniff",
  "Referrer-Policy": "no-referrer",
  "Content-Security-Policy": REPORT_CONTENT_SECURITY_POLICY,
});

function correlationIdFrom(request: Request): string {
  const supplied = correlationIdSchema.safeParse(request.headers.get("x-correlation-id"));
  return supplied.success ? supplied.data : `request:${crypto.randomUUID()}`;
}

function notFoundBody(
  resource: "report" | "source",
  id: string,
  correlationId: string,
): Readonly<Record<string, unknown>> {
  return {
    code: "not_found",
    message: "requested report source was not found",
    correlationId,
    details: { resource, id },
  };
}

function authorized(
  record: Readonly<{ owner: string; scope: string }>,
  principal: HttpPrincipal,
  operationScope: string,
): boolean {
  return (
    record.owner === principal.subject &&
    principal.scopes.includes(operationScope) &&
    principal.scopes.includes(record.scope)
  );
}

function integrityDigest(value: Uint8Array): string {
  return createHash("sha256").update(value).digest("hex");
}

function verifyReportRecord(
  record: ReportArtifactRecord & Readonly<Record<string, unknown>>,
): ReportArtifactRecord {
  const parsed = reportArtifactRecordSchema.parse({
    reportId: record.reportId,
    owner: record.owner,
    scope: record.scope,
    model: record.model,
  });
  const modelJson = canonicalJsonBytes(parsed.model);
  const modelDigest = record.modelSha256;
  const markdownDigest = record.markdownSha256;
  const htmlDigest = record.htmlSha256;
  const cspDigest = record.cspSha256;
  if (
    (record.modelVersion !== undefined && record.modelVersion !== 1) ||
    (record.projectionVersion !== undefined && record.projectionVersion !== 1) ||
    (record.rendererVersion !== undefined && record.rendererVersion !== 1) ||
    (record.modelBytes !== undefined && record.modelBytes !== modelJson.byteLength) ||
    (typeof modelDigest === "string" && modelDigest !== integrityDigest(modelJson))
  )
    throw new Error("report integrity failed");
  const rendered = renderReport(parsed.model);
  const markdownBytes = Buffer.from(rendered.markdown, "utf8");
  const htmlBytes = Buffer.from(rendered.html, "utf8");
  const cspBytes = Buffer.from(rendered.contentSecurityPolicy, "utf8");
  if (
    (record.markdownBytes !== undefined && record.markdownBytes !== markdownBytes.byteLength) ||
    (record.htmlBytes !== undefined && record.htmlBytes !== htmlBytes.byteLength) ||
    (typeof markdownDigest === "string" && markdownDigest !== integrityDigest(markdownBytes)) ||
    (typeof htmlDigest === "string" && htmlDigest !== integrityDigest(htmlBytes)) ||
    (typeof cspDigest === "string" && cspDigest !== integrityDigest(cspBytes))
  )
    throw new Error("report integrity failed");
  return parsed;
}

function verifySourceRecord(
  record: SourceTextRecord & Readonly<Record<string, unknown>>,
): SourceTextRecord {
  const parsed = sourceTextRecordSchema.parse({
    messageId: record.messageId,
    owner: record.owner,
    scope: record.scope,
    text: record.text,
  });
  const sourceJson = canonicalJsonStringBytes(parsed.text);
  if (
    (record.projectionVersion !== undefined && record.projectionVersion !== 1) ||
    (record.sourceTextBytes !== undefined &&
      record.sourceTextBytes !== Buffer.byteLength(parsed.text, "utf8")) ||
    (typeof record.sourceTextSha256 === "string" &&
      record.sourceTextSha256 !== integrityDigest(sourceJson))
  )
    throw new Error("source integrity failed");
  return parsed;
}

function createServingHandlers(repository: ReportServingRepository): OperationHandlerMap {
  const report: OperationHandlerMap["reports.serve"] = async (
    input: unknown,
    context: OperationHandlerContext,
  ) => {
    const request = reportRequestSchema.parse(input);
    const principalJson = canonicalJsonStringBytes(context.principal.subject);
    const record = await repository.resolveReport(request.reportId, principalJson);
    if (
      record === undefined ||
      record.reportId !== request.reportId ||
      !authorized(record, context.principal, REPORT_READ_SCOPE)
    ) {
      return notFoundBody("report", request.reportId, context.correlationId);
    }
    const parsed = verifyReportRecord(record);
    const rendered = renderReport(parsed.model);
    return { kind: "report", reportId: parsed.reportId, body: rendered.html };
  };

  const source: OperationHandlerMap["messages.text"] = async (
    input: unknown,
    context: OperationHandlerContext,
  ) => {
    const request = sourceRequestSchema.parse(input);
    const principalJson = canonicalJsonStringBytes(context.principal.subject);
    const record = await repository.resolveSource(request.messageId, principalJson);
    if (
      record === undefined ||
      record.messageId !== request.messageId ||
      !authorized(record, context.principal, SOURCE_READ_SCOPE)
    ) {
      return notFoundBody("source", request.messageId, context.correlationId);
    }
    const parsed = verifySourceRecord(record);
    return { kind: "source", messageId: parsed.messageId, body: parsed.text };
  };

  return Object.freeze({ "reports.serve": report, "messages.text": source });
}

function jsonResponse(body: unknown, status: number): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...RESPONSE_HEADERS, "Content-Type": "application/json; charset=utf-8" },
  });
}

async function executeServingRoute(
  context: Context,
  options: ReportServingAppOptions,
  operationKey: ServingOperationKey,
  id: string,
): Promise<Response> {
  const request = context.req.raw;
  const correlationId = correlationIdFrom(request);
  const params: Readonly<Record<string, string>> =
    operationKey === "reports.serve" ? { reportId: id } : { messageId: id };
  const adapter = createRegistryTransportAdapter({
    registry: reportServingRegistry,
    handlers: createServingHandlers(options.repository),
    errorRegistry: httpErrorRegistry,
    logger: options.logger,
    authenticate: options.authenticate,
  });
  const result = await adapter.execute(operationKey, params, {
    request,
    correlationId,
    params,
  });
  if (result.status !== 200) return jsonResponse(result.body, result.status);

  const parsed =
    operationKey === "reports.serve"
      ? reportResponseSchema.parse(result.body)
      : sourceResponseSchema.parse(result.body);
  if ("code" in parsed) return jsonResponse(parsed, result.status);
  const headers: Record<string, string> = {
    ...RESPONSE_HEADERS,
    "Content-Type":
      operationKey === "reports.serve" ? "text/html; charset=utf-8" : "text/plain; charset=utf-8",
  };
  return new Response(parsed.body, { status: 200, headers });
}

/** Create isolated authenticated routes for inert reports and text projections. */
export function createReportServingApp(options: ReportServingAppOptions): Hono {
  const app = new Hono();
  app.get("/v1/reports/:reportId", (context) =>
    executeServingRoute(context, options, "reports.serve", context.req.param("reportId")),
  );
  app.get("/v1/messages/:messageId/text", (context) =>
    executeServingRoute(context, options, "messages.text", context.req.param("messageId")),
  );
  app.notFound((context) =>
    jsonResponse(notFoundBody("report", context.req.path, correlationIdFrom(context.req.raw)), 404),
  );
  return app;
}

export { REPORT_READ_SCOPE, SOURCE_READ_SCOPE, RESPONSE_HEADERS };
